namespace POLYGONWARE.Coffee.CoffeeGenerators
{
public enum GeneratorType
{
    BARISTA,
    COFFEE_MACHINE,
    COFFEE_FACTORY,
    COFFEE_CITY,
    COFFEE_PLANET,
    COFFEE_SYSTEM,
    COFFEE_GALAXY,
    COFFEE_UNIVERSE,
    COFFEE_MULTIVERSE,
    COFFEE_OMNIVERSE,
    COFFEE_MEGAPLEX,
    COFFEE_MEGACITY,
    COFFEE_MEGATROPOLIS,
    COFFEE_MEGALOPOLIS,
    COFFEE_MEGALITH,
    COFFEE_MEGALITHIC
}
}